hyperparams_list = [
    {
        'arch': 'kim',
        'name': 'kim_2_3-5',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (5, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_2_4-6',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 64), (6, 96)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_2_5-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 128), (7, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_2_3-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (7, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_3_3-4-5',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (4, 64), (5, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_3_4-5-6',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 64), (5, 128), (6, 96)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_3_5-6-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 128), (6, 96), (7, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_4_3-4-5-6',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (4, 64), (5, 128), (6, 96)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_4_4-5-6-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 64), (5, 128), (6, 96), (7, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_5_3-4-5-6-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (4, 64), (5, 128), (6, 96), (7, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_2_3-5_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (5, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_2_4-6_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 128), (6, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_2_5-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 64), (7, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_2_3-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (7, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_3_3-4-5_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (4, 128), (5, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_3_4-5-6_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 128), (5, 64), (6, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_3_5-6-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 64), (6, 128), (7, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_4_3-4-5-6_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (4, 128), (5, 64), (6, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_4_4-5-6-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 128), (5, 64), (6, 128), (7, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim_5_3-4-5-6-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (4, 128), (5, 64), (6, 128), (7, 128)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_3-5',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (5, 128)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_4-6',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 64), (6, 96)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_5-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 128), (7, 64)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_3-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (7, 64)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_3_3-4-5',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (4, 64), (5, 128)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_3_4-5-6',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 64), (5, 128), (6, 96)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_3_5-6-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 128), (6, 96), (7, 64)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_4_3-4-5-6',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (4, 64), (5, 128), (6, 96)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_4_4-5-6-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 64), (5, 128), (6, 96), (7, 64)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_5_3-4-5-6-7',
        'iterator': 'simple',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 64), (4, 64), (5, 128), (6, 96), (7, 64)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_3-5_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (5, 64)],
        'hidden_units': 16,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_4-6_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 128), (6, 128)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_5-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 64), (7, 128)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_2_3-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (7, 128)],
        'hidden_units': 16,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_3_3-4-5_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (4, 128), (5, 64)],
        'hidden_units': 16,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_3_4-5-6_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 128), (5, 64), (6, 128)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_3_5-6-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(5, 64), (6, 128), (7, 128)],
        'hidden_units': 32,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_4_3-4-5-6_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (4, 128), (5, 64), (6, 128)],
        'hidden_units': 16,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_4_4-5-6-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(4, 128), (5, 64), (6, 128), (7, 128)],
        'hidden_units': 128,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved_5_3-4-5-6-7_early',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 128), (4, 128), (5, 64), (6, 128), (7, 128)],
        'hidden_units': 16,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 301,
        'epoch_print_cost': 5,
        'minibatch_size': 32,
        'keep_prob': 0.5
    }
]
