hyperparams_list = [
    {
        'arch': 'kim',
        'name': 'kim01',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 96), (5, 96), (7, 64)],
        'num_labels': 5,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 1,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved01',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 96), (5, 96), (7, 64)],
        'hidden_units': 64,
        'num_labels': 5,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 1,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'kim',
        'name': 'kim02',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 96), (5, 96), (7, 64)],
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 1,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved02',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 96), (5, 96), (7, 64)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 1,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved03',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 96), (4, 96), (5, 96)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 1,
        'minibatch_size': 32,
        'keep_prob': 0.5
    },
    {
        'arch': 'evolved',
        'name': 'evolved04',
        'iterator': 'early_stop',
        'sentence_length': 100,
        'word_dimension': 300,
        'filters_size': [(3, 96), (4, 96), (5, 64)],
        'hidden_units': 64,
        'num_labels': 3,
        'learning_rate': 0.009,
        'epochs': 201,
        'epoch_print_cost': 1,
        'minibatch_size': 32,
        'keep_prob': 0.5
    }
]
